/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.liblibai.openapi.client.model;

import cloud.liblibai.openapi.client.model.ComfyStatusResponseDataVideosInner;
import cloud.liblibai.openapi.client.model.GenerateStatus;
import cloud.liblibai.openapi.client.model.NodeImage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ComfyStatusResponseData
 */
public class ComfyStatusResponseDataTest {
    private final ComfyStatusResponseData model = new ComfyStatusResponseData();

    /**
     * Model tests for ComfyStatusResponseData
     */
    @Test
    public void testComfyStatusResponseData() {
        // TODO: test ComfyStatusResponseData
    }

    /**
     * Test the property 'accountBalance'
     */
    @Test
    public void accountBalanceTest() {
        // TODO: test accountBalance
    }

    /**
     * Test the property 'generateStatus'
     */
    @Test
    public void generateStatusTest() {
        // TODO: test generateStatus
    }

    /**
     * Test the property 'generateUuid'
     */
    @Test
    public void generateUuidTest() {
        // TODO: test generateUuid
    }

    /**
     * Test the property 'percentCompleted'
     */
    @Test
    public void percentCompletedTest() {
        // TODO: test percentCompleted
    }

    /**
     * Test the property 'pointsCost'
     */
    @Test
    public void pointsCostTest() {
        // TODO: test pointsCost
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'videos'
     */
    @Test
    public void videosTest() {
        // TODO: test videos
    }

}
