/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.liblibai.openapi.client.model;

import cloud.liblibai.openapi.client.model.UltraControlNet;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImageToImageUltraRequestGenerateParams
 */
public class ImageToImageUltraRequestGenerateParamsTest {
    private final ImageToImageUltraRequestGenerateParams model = new ImageToImageUltraRequestGenerateParams();

    /**
     * Model tests for ImageToImageUltraRequestGenerateParams
     */
    @Test
    public void testImageToImageUltraRequestGenerateParams() {
        // TODO: test ImageToImageUltraRequestGenerateParams
    }

    /**
     * Test the property 'prompt'
     */
    @Test
    public void promptTest() {
        // TODO: test prompt
    }

    /**
     * Test the property 'sourceImage'
     */
    @Test
    public void sourceImageTest() {
        // TODO: test sourceImage
    }

    /**
     * Test the property 'imgCount'
     */
    @Test
    public void imgCountTest() {
        // TODO: test imgCount
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

    /**
     * Test the property 'controlnet'
     */
    @Test
    public void controlnetTest() {
        // TODO: test controlnet
    }

}
