/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.liblibai.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InpaintParams
 */
public class InpaintParamsTest {
    private final InpaintParams model = new InpaintParams();

    /**
     * Model tests for InpaintParams
     */
    @Test
    public void testInpaintParams() {
        // TODO: test InpaintParams
    }

    /**
     * Test the property 'maskImage'
     */
    @Test
    public void maskImageTest() {
        // TODO: test maskImage
    }

    /**
     * Test the property 'maskBlur'
     */
    @Test
    public void maskBlurTest() {
        // TODO: test maskBlur
    }

    /**
     * Test the property 'maskPadding'
     */
    @Test
    public void maskPaddingTest() {
        // TODO: test maskPadding
    }

    /**
     * Test the property 'maskMode'
     */
    @Test
    public void maskModeTest() {
        // TODO: test maskMode
    }

    /**
     * Test the property 'inpaintArea'
     */
    @Test
    public void inpaintAreaTest() {
        // TODO: test inpaintArea
    }

    /**
     * Test the property 'inpaintingFill'
     */
    @Test
    public void inpaintingFillTest() {
        // TODO: test inpaintingFill
    }

}
