/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ControlNet
 */
public class ControlNetTest {
    private final ControlNet model = new ControlNet();

    /**
     * Model tests for ControlNet
     */
    @Test
    public void testControlNet() {
        // TODO: test ControlNet
    }

    /**
     * Test the property 'unitOrder'
     */
    @Test
    public void unitOrderTest() {
        // TODO: test unitOrder
    }

    /**
     * Test the property 'sourceImage'
     */
    @Test
    public void sourceImageTest() {
        // TODO: test sourceImage
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'preprocessor'
     */
    @Test
    public void preprocessorTest() {
        // TODO: test preprocessor
    }

    /**
     * Test the property 'annotationParameters'
     */
    @Test
    public void annotationParametersTest() {
        // TODO: test annotationParameters
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'controlWeight'
     */
    @Test
    public void controlWeightTest() {
        // TODO: test controlWeight
    }

    /**
     * Test the property 'startingControlStep'
     */
    @Test
    public void startingControlStepTest() {
        // TODO: test startingControlStep
    }

    /**
     * Test the property 'endingControlStep'
     */
    @Test
    public void endingControlStepTest() {
        // TODO: test endingControlStep
    }

    /**
     * Test the property 'pixelPerfect'
     */
    @Test
    public void pixelPerfectTest() {
        // TODO: test pixelPerfect
    }

    /**
     * Test the property 'controlMode'
     */
    @Test
    public void controlModeTest() {
        // TODO: test controlMode
    }

    /**
     * Test the property 'resizeMode'
     */
    @Test
    public void resizeModeTest() {
        // TODO: test resizeMode
    }

    /**
     * Test the property 'maskImage'
     */
    @Test
    public void maskImageTest() {
        // TODO: test maskImage
    }

}
