/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.liblib.openapi.client.model.GenerateStatus;
import org.liblib.openapi.client.model.Image;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatusResponseData
 */
public class StatusResponseDataTest {
    private final StatusResponseData model = new StatusResponseData();

    /**
     * Model tests for StatusResponseData
     */
    @Test
    public void testStatusResponseData() {
        // TODO: test StatusResponseData
    }

    /**
     * Test the property 'generateUuid'
     */
    @Test
    public void generateUuidTest() {
        // TODO: test generateUuid
    }

    /**
     * Test the property 'generateStatus'
     */
    @Test
    public void generateStatusTest() {
        // TODO: test generateStatus
    }

    /**
     * Test the property 'percentCompleted'
     */
    @Test
    public void percentCompletedTest() {
        // TODO: test percentCompleted
    }

    /**
     * Test the property 'generateMsg'
     */
    @Test
    public void generateMsgTest() {
        // TODO: test generateMsg
    }

    /**
     * Test the property 'pointsCost'
     */
    @Test
    public void pointsCostTest() {
        // TODO: test pointsCost
    }

    /**
     * Test the property 'accountBalance'
     */
    @Test
    public void accountBalanceTest() {
        // TODO: test accountBalance
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

}
