/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.liblib.openapi.client.model.TextToImageRequestGenerateParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TextToImageRequest
 */
public class TextToImageRequestTest {
    private final TextToImageRequest model = new TextToImageRequest();

    /**
     * Model tests for TextToImageRequest
     */
    @Test
    public void testTextToImageRequest() {
        // TODO: test TextToImageRequest
    }

    /**
     * Test the property 'templateUuid'
     */
    @Test
    public void templateUuidTest() {
        // TODO: test templateUuid
    }

    /**
     * Test the property 'generateParams'
     */
    @Test
    public void generateParamsTest() {
        // TODO: test generateParams
    }

}
