/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.liblib.openapi.client.model.TextToImageUltraRequestGenerateParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TextToImageUltraRequest
 */
public class TextToImageUltraRequestTest {
    private final TextToImageUltraRequest model = new TextToImageUltraRequest();

    /**
     * Model tests for TextToImageUltraRequest
     */
    @Test
    public void testTextToImageUltraRequest() {
        // TODO: test TextToImageUltraRequest
    }

    /**
     * Test the property 'templateUuid'
     */
    @Test
    public void templateUuidTest() {
        // TODO: test templateUuid
    }

    /**
     * Test the property 'generateParams'
     */
    @Test
    public void generateParamsTest() {
        // TODO: test generateParams
    }

}
