/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TextToImageRequestGenerateParamsHiResFixInfo
 */
public class TextToImageRequestGenerateParamsHiResFixInfoTest {
    private final TextToImageRequestGenerateParamsHiResFixInfo model = new TextToImageRequestGenerateParamsHiResFixInfo();

    /**
     * Model tests for TextToImageRequestGenerateParamsHiResFixInfo
     */
    @Test
    public void testTextToImageRequestGenerateParamsHiResFixInfo() {
        // TODO: test TextToImageRequestGenerateParamsHiResFixInfo
    }

    /**
     * Test the property 'hiresSteps'
     */
    @Test
    public void hiresStepsTest() {
        // TODO: test hiresSteps
    }

    /**
     * Test the property 'hiresDenoisingStrength'
     */
    @Test
    public void hiresDenoisingStrengthTest() {
        // TODO: test hiresDenoisingStrength
    }

    /**
     * Test the property 'upscaler'
     */
    @Test
    public void upscalerTest() {
        // TODO: test upscaler
    }

    /**
     * Test the property 'resizedWidth'
     */
    @Test
    public void resizedWidthTest() {
        // TODO: test resizedWidth
    }

    /**
     * Test the property 'resizedHeight'
     */
    @Test
    public void resizedHeightTest() {
        // TODO: test resizedHeight
    }

}
