/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VersionResponse
 */
public class VersionResponseTest {
    private final VersionResponse model = new VersionResponse();

    /**
     * Model tests for VersionResponse
     */
    @Test
    public void testVersionResponse() {
        // TODO: test VersionResponse
    }

    /**
     * Test the property 'versionUuid'
     */
    @Test
    public void versionUuidTest() {
        // TODO: test versionUuid
    }

    /**
     * Test the property 'modelName'
     */
    @Test
    public void modelNameTest() {
        // TODO: test modelName
    }

    /**
     * Test the property 'versionName'
     */
    @Test
    public void versionNameTest() {
        // TODO: test versionName
    }

    /**
     * Test the property 'baseAlgo'
     */
    @Test
    public void baseAlgoTest() {
        // TODO: test baseAlgo
    }

    /**
     * Test the property 'showType'
     */
    @Test
    public void showTypeTest() {
        // TODO: test showType
    }

    /**
     * Test the property 'commercialUse'
     */
    @Test
    public void commercialUseTest() {
        // TODO: test commercialUse
    }

    /**
     * Test the property 'modelUrl'
     */
    @Test
    public void modelUrlTest() {
        // TODO: test modelUrl
    }

}
