/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.liblibai.openapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 可商用标识，可商用为1，不可商用为0
 */
@JsonAdapter(CommercialUseEnum.Adapter.class)
public enum CommercialUseEnum {
  
  NoCommercialUse("0"),
  
  CommercialUse("1");

  private String value;

  CommercialUseEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CommercialUseEnum fromValue(String value) {
    for (CommercialUseEnum b : CommercialUseEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CommercialUseEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final CommercialUseEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CommercialUseEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CommercialUseEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CommercialUseEnum.fromValue(value);
  }
}

