/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.liblibai.openapi.client.model;

import java.util.Objects;
import cloud.liblibai.openapi.client.model.CommercialUseEnum;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.liblibai.openapi.client.JSON;

/**
 * VersionResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-18T11:30:46.149751821+08:00[Asia/Shanghai]", comments = "Generator version: 7.10.0")
public class VersionResponseData {
  public static final String SERIALIZED_NAME_VERSION_UUID = "versionUuid";
  @SerializedName(SERIALIZED_NAME_VERSION_UUID)
  @javax.annotation.Nullable
  private String versionUuid;

  public static final String SERIALIZED_NAME_MODEL_NAME = "modelName";
  @SerializedName(SERIALIZED_NAME_MODEL_NAME)
  @javax.annotation.Nullable
  private String modelName;

  public static final String SERIALIZED_NAME_VERSION_NAME = "versionName";
  @SerializedName(SERIALIZED_NAME_VERSION_NAME)
  @javax.annotation.Nullable
  private String versionName;

  public static final String SERIALIZED_NAME_BASE_ALGO = "baseAlgo";
  @SerializedName(SERIALIZED_NAME_BASE_ALGO)
  @javax.annotation.Nullable
  private String baseAlgo;

  public static final String SERIALIZED_NAME_BASE_ALGO_NAME = "baseAlgoName";
  @SerializedName(SERIALIZED_NAME_BASE_ALGO_NAME)
  @javax.annotation.Nullable
  private String baseAlgoName;

  public static final String SERIALIZED_NAME_SHOW_TYPE = "showType";
  @SerializedName(SERIALIZED_NAME_SHOW_TYPE)
  @javax.annotation.Nullable
  private String showType;

  public static final String SERIALIZED_NAME_COMMERCIAL_USE = "commercialUse";
  @SerializedName(SERIALIZED_NAME_COMMERCIAL_USE)
  @javax.annotation.Nullable
  private CommercialUseEnum commercialUse;

  public static final String SERIALIZED_NAME_MODEL_URL = "modelUrl";
  @SerializedName(SERIALIZED_NAME_MODEL_URL)
  @javax.annotation.Nullable
  private String modelUrl;

  public VersionResponseData() {
  }

  public VersionResponseData versionUuid(@javax.annotation.Nullable String versionUuid) {
    this.versionUuid = versionUuid;
    return this;
  }

  /**
   * LiblibAI官网模型链接后缀
   * @return versionUuid
   */
  @javax.annotation.Nullable
  public String getVersionUuid() {
    return versionUuid;
  }

  public void setVersionUuid(@javax.annotation.Nullable String versionUuid) {
    this.versionUuid = versionUuid;
  }


  public VersionResponseData modelName(@javax.annotation.Nullable String modelName) {
    this.modelName = modelName;
    return this;
  }

  /**
   * 模型名称
   * @return modelName
   */
  @javax.annotation.Nullable
  public String getModelName() {
    return modelName;
  }

  public void setModelName(@javax.annotation.Nullable String modelName) {
    this.modelName = modelName;
  }


  public VersionResponseData versionName(@javax.annotation.Nullable String versionName) {
    this.versionName = versionName;
    return this;
  }

  /**
   * 版本名称
   * @return versionName
   */
  @javax.annotation.Nullable
  public String getVersionName() {
    return versionName;
  }

  public void setVersionName(@javax.annotation.Nullable String versionName) {
    this.versionName = versionName;
  }


  public VersionResponseData baseAlgo(@javax.annotation.Nullable String baseAlgo) {
    this.baseAlgo = baseAlgo;
    return this;
  }

  /**
   * 基础算法
   * @return baseAlgo
   */
  @javax.annotation.Nullable
  public String getBaseAlgo() {
    return baseAlgo;
  }

  public void setBaseAlgo(@javax.annotation.Nullable String baseAlgo) {
    this.baseAlgo = baseAlgo;
  }


  public VersionResponseData baseAlgoName(@javax.annotation.Nullable String baseAlgoName) {
    this.baseAlgoName = baseAlgoName;
    return this;
  }

  /**
   * 算法名称
   * @return baseAlgoName
   */
  @javax.annotation.Nullable
  public String getBaseAlgoName() {
    return baseAlgoName;
  }

  public void setBaseAlgoName(@javax.annotation.Nullable String baseAlgoName) {
    this.baseAlgoName = baseAlgoName;
  }


  public VersionResponseData showType(@javax.annotation.Nullable String showType) {
    this.showType = showType;
    return this;
  }

  /**
   * 公开可用的模型标识
   * @return showType
   */
  @javax.annotation.Nullable
  public String getShowType() {
    return showType;
  }

  public void setShowType(@javax.annotation.Nullable String showType) {
    this.showType = showType;
  }


  public VersionResponseData commercialUse(@javax.annotation.Nullable CommercialUseEnum commercialUse) {
    this.commercialUse = commercialUse;
    return this;
  }

  /**
   * Get commercialUse
   * @return commercialUse
   */
  @javax.annotation.Nullable
  public CommercialUseEnum getCommercialUse() {
    return commercialUse;
  }

  public void setCommercialUse(@javax.annotation.Nullable CommercialUseEnum commercialUse) {
    this.commercialUse = commercialUse;
  }


  public VersionResponseData modelUrl(@javax.annotation.Nullable String modelUrl) {
    this.modelUrl = modelUrl;
    return this;
  }

  /**
   * 模型链接
   * @return modelUrl
   */
  @javax.annotation.Nullable
  public String getModelUrl() {
    return modelUrl;
  }

  public void setModelUrl(@javax.annotation.Nullable String modelUrl) {
    this.modelUrl = modelUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionResponseData versionResponseData = (VersionResponseData) o;
    return Objects.equals(this.versionUuid, versionResponseData.versionUuid) &&
        Objects.equals(this.modelName, versionResponseData.modelName) &&
        Objects.equals(this.versionName, versionResponseData.versionName) &&
        Objects.equals(this.baseAlgo, versionResponseData.baseAlgo) &&
        Objects.equals(this.baseAlgoName, versionResponseData.baseAlgoName) &&
        Objects.equals(this.showType, versionResponseData.showType) &&
        Objects.equals(this.commercialUse, versionResponseData.commercialUse) &&
        Objects.equals(this.modelUrl, versionResponseData.modelUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionUuid, modelName, versionName, baseAlgo, baseAlgoName, showType, commercialUse, modelUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionResponseData {\n");
    sb.append("    versionUuid: ").append(toIndentedString(versionUuid)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    versionName: ").append(toIndentedString(versionName)).append("\n");
    sb.append("    baseAlgo: ").append(toIndentedString(baseAlgo)).append("\n");
    sb.append("    baseAlgoName: ").append(toIndentedString(baseAlgoName)).append("\n");
    sb.append("    showType: ").append(toIndentedString(showType)).append("\n");
    sb.append("    commercialUse: ").append(toIndentedString(commercialUse)).append("\n");
    sb.append("    modelUrl: ").append(toIndentedString(modelUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("versionUuid");
    openapiFields.add("modelName");
    openapiFields.add("versionName");
    openapiFields.add("baseAlgo");
    openapiFields.add("baseAlgoName");
    openapiFields.add("showType");
    openapiFields.add("commercialUse");
    openapiFields.add("modelUrl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VersionResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VersionResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VersionResponseData is not found in the empty JSON string", VersionResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VersionResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VersionResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("versionUuid") != null && !jsonObj.get("versionUuid").isJsonNull()) && !jsonObj.get("versionUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `versionUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("versionUuid").toString()));
      }
      if ((jsonObj.get("modelName") != null && !jsonObj.get("modelName").isJsonNull()) && !jsonObj.get("modelName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `modelName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modelName").toString()));
      }
      if ((jsonObj.get("versionName") != null && !jsonObj.get("versionName").isJsonNull()) && !jsonObj.get("versionName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `versionName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("versionName").toString()));
      }
      if ((jsonObj.get("baseAlgo") != null && !jsonObj.get("baseAlgo").isJsonNull()) && !jsonObj.get("baseAlgo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `baseAlgo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baseAlgo").toString()));
      }
      if ((jsonObj.get("baseAlgoName") != null && !jsonObj.get("baseAlgoName").isJsonNull()) && !jsonObj.get("baseAlgoName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `baseAlgoName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baseAlgoName").toString()));
      }
      if ((jsonObj.get("showType") != null && !jsonObj.get("showType").isJsonNull()) && !jsonObj.get("showType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `showType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("showType").toString()));
      }
      // validate the optional field `commercialUse`
      if (jsonObj.get("commercialUse") != null && !jsonObj.get("commercialUse").isJsonNull()) {
        CommercialUseEnum.validateJsonElement(jsonObj.get("commercialUse"));
      }
      if ((jsonObj.get("modelUrl") != null && !jsonObj.get("modelUrl").isJsonNull()) && !jsonObj.get("modelUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `modelUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modelUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VersionResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VersionResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VersionResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VersionResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<VersionResponseData>() {
           @Override
           public void write(JsonWriter out, VersionResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VersionResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VersionResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VersionResponseData
   * @throws IOException if the JSON string is invalid with respect to VersionResponseData
   */
  public static VersionResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VersionResponseData.class);
  }

  /**
   * Convert an instance of VersionResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

