/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets auditStatus
 */
@JsonAdapter(AuditStatus.Adapter.class)
public enum AuditStatus {
  
  PENDING(1),
  
  APPROVING(2),
  
  APPROVED(3),
  
  REJECTED(4),
  
  FAILED(5);

  private Integer value;

  AuditStatus(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AuditStatus fromValue(Integer value) {
    for (AuditStatus b : AuditStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AuditStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final AuditStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AuditStatus read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return AuditStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    AuditStatus.fromValue(value);
  }
}

