/*
 * LiblibAI API
 * LiblibAI x 星流 图像大模型API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.liblib.openapi.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets generateStatus
 */
@JsonAdapter(GenerateStatus.Adapter.class)
public enum GenerateStatus {
  
  PENDING(1),
  
  RUNNING(2),
  
  GENERATED(3),
  
  APPROVING(4),
  
  SUCCEED(5),
  
  FAILED(6);

  private Integer value;

  GenerateStatus(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GenerateStatus fromValue(Integer value) {
    for (GenerateStatus b : GenerateStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<GenerateStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final GenerateStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GenerateStatus read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return GenerateStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    GenerateStatus.fromValue(value);
  }
}

